head: 
   favicon: "/assets/images/Domain/D-IM16.jpg" #  the favicon
   high_res_favicon: "/assets/images/Domain/D-IM16.jpg" #  the favicon using high quality format
   apple_touch_icon: "https://ooo.0o0.ooo/2017/06/08/5939484dc618e.png" # the iOS Home button icon
   keywords: "冷筱华, 游戏, 个人网站, 摸鱼, 冷萌萌, 5d chess, 明日方舟, arknights， 英雄联盟, 单机游戏" #  the site keywords

uiux:
   android_chrome_color: "#eeeeee" #  the color of the Chrome address bar
   nprogress_color: "#29d" #  the color of the top loading progress bar
   nprogress_buffer: 200 # the top loading progress bar buffers
   meng: true

background: 
   purecolor: "#eeeeee" # the background color

img: 
   avatar: "/assets/images/Domain/D-IM16.jpg" # your avatar

card: 
   card_shadow: 1 # card shadow (0-24), 0 is not displayed
   card_hoverable: false # When the hover to deepen the shadow

many_authors: false

sns_share: # SNS Share Switch
   twitter: true
   facebook: false
   googleplus: false
   weibo: true
   linkedin: false
   qq: true
   telegram: true

comment:
  used: "gitalk" # disqus,livere,gitment,valine,gitalk,twikoo
  # disqus config
  disqus_shortname: "lxh-wxdt" # Your disqus 
  disqus_button: true # disqus load button
  disqus_proxy: false # # disqus proxy(Do not use)
  disqus_proxy_url: "" # (Do not use)
  disqus_api_key: "" # (Do not use)
  # livere config
  livere_type: 'city'
  livere_data_uid: ''
  # gitment config
  owner: "IceMoeMoe"
  repo: "Gitment-Data"
  client_id: "65afb6c07010d1b64d3c"
  client_secret: "e30ae10f304038da6f59ed86b3d549830d808514"
  # valine config
  valine_app_id: ''
  valine_app_key: ''
  valine_placeholder: "ヾﾉ≧∀≦)o来啊，快活啊!"
  # gitalk config
  gitalk:
    client_id: "65afb6c07010d1b64d3c"
    client_secret: "e30ae10f304038da6f59ed86b3d549830d808514"
    repo: "Gitalk-Data"
    owner: "IceMoeMoe"
    admin: ["Android-KitKat", "shakugannosaints"]
  twikoo:
    envId: ""
    region: ""
    option: ""

prism:
  themes: prism-okaidia
  components: 
    - bash 
  plugins: 

google_analytics: "UA-181030602-1"  # google analytics code

lang: "zh-CN"  # lang

deploy: "" # if you used coding pages

custom_css: "customCss.css" # Use the assets/css/customCss.css

custom_js: "" # Use the assets/js/customJS.js